/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as external from "./external";
export type { external };
export type { NFT } from "./NFT";
