/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721AUpgradeableSol from "./ERC721AUpgradeable.sol";
export type { erc721AUpgradeableSol };
export type { ERC721AURIStorageUpgradeable } from "./ERC721AURIStorageUpgradeable";
